### ISSUE TITLE
Does Rapid-XAML-Toolkit support Xamarin.Forms?

### ISSUE THREAD

**Issue by MichaelStgt** [mrlacey/Rapid-XAML-Toolkit#335]
Dear mrlacey,

i like your extension, but after going through your repositories i have seen your work is mostly related to Windows UWP. As I do only work with Xamarin.Forms, do/will you implement your extension for the special Xamarin.Forms Xaml elements to?

**Comment by mrlacey** [comment]
@MichaelStgt Yes everything technically works with Xamarin.Forms, UWP, and WPF.
It's quicker for me to test with UWP so that's why there's more for it at the moment but other functionality for Xamarin.Forms is coming.
Are there any particular things you want to see or any obvious gaps?

**Comment by MichaelStgt** [comment]
What really would be a nice feature would be to suppress messages like in StyleCop.Analyzer. One example would be to suppress all messages relating to controls assigned to a Grid.Column or Grid.Row that does not exist. During development, I often shift around controls into containers, but leave the Grid.Column/Row Settings in to go back if something does not work. I am to encountered some performance issues, but that may be related to one of my other add-ins or yours is colluding with something else.

**Comment by mrlacey** [comment]
Because I couldn't hook them into the native Visual Studio infrastructure for configuring analyzers but it's possible to configure it in a different way.

The easiest is via the quick actions menu. When an action/fix/suggestion is available, so if the option to suppress such warnings in future.
Just select the `Do not warn about ...` option

![image](https://user-images.githubusercontent.com/189547/77520933-d614b180-6e79-11ea-9051-55c3e0f56b78.png)

This will create (or add to) a file called `settings.xamlAnalysis` that contains a JSON array or codes and how to warn about them. Including hiding/suppressing them entirely.

![image](https://user-images.githubusercontent.com/189547/77521476-a619de00-6e7a-11ea-8df9-ed586d4f0405.png)


https://github.com/mrlacey/Rapid-XAML-Toolkit/blob/master/docs/configuring-analysis.md contains details of other options for changing how and what is reported. 
It's also possible to suppress individual reports or reports within a single file.

**Comment by MichaelStgt** [comment]
wow. this is just awesome!

**Comment by mrlacey** [comment]
Leaving this open until more Xamarin.Forms related analysis is added

**Comment by mrlacey** [comment]
Xamarin.Forms is supported and [the latest release (v 0.12.0)](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.RapidXamlToolkit) includes more XF specific functionality.
