### ISSUE TITLE
remove actions that aren't working

### ISSUE THREAD

**Issue by mrlacey** [mrlacey/Rapid-XAML-Toolkit#404]
Remove 404 links * greetings actions as they're not working as intended

See
https://github.com/restqa/404-links/issues/4

https://github.com/actions/first-interaction/issues/10

**Comment by olivierodo** [comment]
Regarding the 404-link issue, it has been fixed.
The root cause was because of :
https://github.com/mrlacey/Rapid-XAML-Toolkit/blob/15453220a95745240e8c9461f7f37a79c3988f50/docs/warnings/_template.md#L23

So i handle that case in the 404-link github action and bump the version used by this project with a pull request.

**Comment by mrlacey** [comment]
reopening to remove the greetings workflow.
