### ISSUE TITLE
Profile Editor incorrect item selection

### ISSUE THREAD

**Issue by andrea-bigi-ems** [mrlacey/Rapid-XAML-Toolkit#499]
### Describe the bug

hello,

the profile editor doesn't allow to edit the currently selected profile.

![image](https://user-images.githubusercontent.com/90207456/140894387-819e5abc-7a6f-4999-8b19-ca6c1ea1d76c.png)

### How can this be reproduced?

see screenshot

### Which version of Visual Studio are you using?

- [X] 2019
- [ ] 2019 (preview)

### Project Type

WPF

**Comment by mrlacey** [comment]
I've tried to address this several times over the past few months but have never been able to work out what the issue was on those attempts.
Today, I found what looks like a trivial fix and one that seems to work in all scenarios too. 
V0.13.2 is just been uploaded to the marketplace and should be available shortly.
