### ISSUE TITLE
Format the generated code

### ISSUE THREAD

**Issue by ArchieCoder** [mrlacey/Rapid-XAML-Toolkit#62]
First of all, great job for doing this tool!

I tried to generate the code with the provided ViewModel. Would it be possible to apply the default VS format to make the output cuter?

![sample](https://user-images.githubusercontent.com/1608424/39665695-0d8f37ea-5066-11e8-94c9-4ce465c0fbeb.png)

**Comment by mrlacey** [comment]
I'm not against doing this but it's a lot of work for something that VS can do for you with 3-keystrokes (ctrl + k, d) and one of the principles of this project is to focus on things that VS can't already do.

I admit, the argument for doing this is stronger when generating the whole view but that itself was a late addition.
The starting point for the project was working with existing views (via clipboard and toolbox) and when adding to the view that way we can't add the spacing as we don't know what will be appropriate.

If anyone else thinks this is important, please speak up and that will help with prioritization.

**Comment by mrlacey** [comment]
Been thinking more about this, would be good to do as the current behavior is currently a poor first impression.

If did this, would need to determine the indent level from the rest of the content on the page. (or could just default to 4 spaces?)

Looked at using `XDocument` to format the whole page but that risks changing other configured content.
Can't just format the XAML generated from the VM as that may reference namespaces in the rest of the document.

**Comment by ArchieCoder** [comment]
I haven't check how you did the actual code injection in the project or existing file, but if I recall 10 years ago when I worked with controlling VS, you could call VS api (OLE!?). Could it be possible to just call VS api?

**Comment by mrlacey** [comment]
> I haven't check how you did the actual code injection in the project or existing file, but if I recall 10 years ago when I worked with controlling VS, you could call VS api (OLE!?). Could it be possible to just call VS api?

Calling the VS command (if can identify how) would need to be done only once the generated file was opened and has possible timing issues.

investigation continues....

**Comment by mrlacey** [comment]
Note to self: Try doing this with the "Edit.FormatDocument" command.

**Comment by mrlacey** [comment]
I had a look at trying to trigger the built-in document formatting when generating the View from the ViewModel but there isn't an easy way to determine when the generated file has been opened in the designer (requesting opening the doc is fire-and-forget) and so the command can be correctly applied.
This would have been better than nothing but would have been an incomplete solution to improving formatting of the generated code as it wouldn't apply to files not directly opened or anything put in the clipboard, toolbox, or anywhere else.

I'm now warming to the idea of applying default formatting to the generated XAML. This might not match any custom settings configured at the project or user level but I think this will be better than nothing. If it doesn't match then it's no worse than what we have now, which is relying on the user to trigger formatting themselves.

Need to look at using [`LanguagePreferences.IndentSize`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.package.languagepreferences.indentsize?view=visualstudiosdk-2017#Microsoft_VisualStudio_Package_LanguagePreferences_IndentSize) to know what size indent to use. Otherwsie get `IndentSize.Default`

**Comment by PieEatingNinjas** [comment]
The ExecuteCommand does work in, for example, SetDataContextCommand as you have the relevant file open at the moment. Implemented it there and it works nice.

The diffculty is indeed when generating the View file. I got it more or less working though, the only thing I'm currently not able to work around is the fact that whenever the generated view opens in the XAML/Designer split view the "Edit.FormatDocument" command doesn't work. This only works when the XAML view gets focus. An Exception is thrown when executing the command while the Designer has focus. 
If there should be a way to open the generated document and force focus on the XAML view, it should work...

I personally would prefer the "Edit.FormatDocument" command approach instead of applying default formatting to generated XAML.

**Comment by mrlacey** [comment]
@PieEatingNinjas yes,  being able to use "Edit.FormatDocument" would be better for files that are generated and opened. Applying the formatting directly will mean that all the generated XAML can be formatted.

**Comment by mrlacey** [comment]
Have explored in a [branch](https://github.com/Microsoft/Rapid-XAML-Toolkit/tree/Issue62) so instead of getting

![image](https://user-images.githubusercontent.com/189547/47937129-adcc9180-ded7-11e8-920b-5a60e823cd05.png)

now get

![image](https://user-images.githubusercontent.com/189547/47937157-c0df6180-ded7-11e8-9312-48a7d75126a0.png)

Indent amount comes from VS setting for XAML

Haven't yet applied the formatting to all XAML generation.

Unresolved:
- Is this better than nothing, in that there are edge cases where this won't always be correct? (.editorconfig and XAMLStyler may want to do different things)
- It doesn't address formatting C#/VB code (where this is generated for codebehind)
- Should all XAML be formatted this way?

**Comment by PieEatingNinjas** [comment]
Looks good!

- C#/VB formatting can be easily done by triggering the FormatDocument command ([see my commit](https://github.com/PieEatingNinjas/Rapid-XAML-Toolkit/commit/a1825ba612dec944feb4796acf622a6918c9a32d))
        (if you want to take this approach, I think we could create an extension method on DTE which triggers the format command so that we can easily call it wherever code is generated

- I think all XAML should be formatted this way

If there is anything you want me to do, let me know!

**Comment by mrlacey** [comment]
The FormatDocument command only works on C#/VB code in the activedocument window. It doesn't work for newly created files that aren't open.

There's a balance that needs to be found with making sure that generated code added to a document that already exists matches the formatting of existing code and not doing more than advertised/expected.
If a person selects a command "Set Datacontext" and it additionally reformats an existing document that leads to large, unexpected changes that could be a bad thing.
My thinking is that while it's good to apply consistent formatting where possible, it should be opt-out. As such, I've created a new setting to allow this to be disabled if not desired. It will also be a separate entry in the undo stack so can be reverted that way also.
As a new setting, this must be enabled or profiles reset (it's enabled in all default profiles.)
Nerw setting created at profile level as it relates to formatting and all other formatting settings are tied to profiles.

I'm setting this to run on (active/open) XAML and code-behind files when setting the DataContext

**Comment by mrlacey** [comment]
So, I gave in and wrote the code to reformat all XAML. Even that copied to the clipboard or toolbox.
The least fun part was changing all the expected values in dozens of tests so the expected XAML was indented as it should be.
